### ISSUE TITLE
linux install without virtualbox

### ISSUE THREAD

**Issue by gregwebs** [CenturyLinkLabs/panamax-ui#341]
Why does the linux install need virtualbox/vagrant? The linux install should be able to just assume docker is installled. This stopped me from trying out panamax.

**Comment by madkinder** [comment]
I second this. I became very excited when first discovered Panamax. But then quickly got disappointed - why would one install VirtualBox on a Linux developer environment? Moreover - on a production server.

I understand that Panamax requires CoreOS, but why not use KVM then? Yes, KVM is not available on MacOS. But nobody runs servers on Macs anyway :) If you run your servers on your own hardware you're probably using Linux anyways. Or you can run CoreOS on AWS.

Are there any instructions how can a manually installed CoreOS be used with Panamax eliminating the need of VirtualBox?

**Comment by patocox** [comment]
@madkinder Check out https://github.com/CenturyLinkLabs/panamax-ui/wiki/Cloud-Provider-Installation-of-Panamax-Client . You can install Panamax on a VM running CoreOS w/o VirtualBox.

**Comment by rossjimenez** [comment]
@madkinder Panamax is meant to be a client tool that runs locally, initially that was easiest using virtualbox.  We do have the ability to deploy to remote infrastructures where either CoreOS or Kubernetes clusters are setup. http://j.mp/pmx_installagent

You can install Panamax directly on CoreOS but we don't recommend it given we don't have any security built into the panamax client. https://github.com/CenturyLinkLabs/panamax-ui/wiki/Cloud-Provider-Installation-of-Panamax-Client

**Comment by JemiloII** [comment]
I'm just noting the fact that it's on a vm killed my use for it. Even for the coreos side. I'll just go back to shipyard until this can be a standalone install on linux without a vm.

**Comment by rubenst2013** [comment]
2016 and still the same. I got very exited too but then the disappointment in the UNLISTED TL;DR and costly third party requirements panamax still has. 

back to the drawing board for me. :/
