### ISSUE TITLE
fails to run any image

### ISSUE THREAD

**Issue by lgs** [CenturyLinkLabs/panamax-ui#344]
I Search Panamax Templates & Docker Repositories for `lgsd/docker-rails`, then I click "Run the image" but get the following error looping infinitely:

<pre>
Sep 02 21:02:17 systemd Started lgsd_docker-rails_latest.service.
Sep 02 21:02:17 docker Error response from daemon: No such container: lgsd_docker-rails_latest
Sep 02 21:02:17 docker 2014/09/02 19:02:17 Error: failed to kill one or more containers
Sep 02 21:02:17 docker Error response from daemon: No such container: lgsd_docker-rails_latest
Sep 02 21:02:17 docker 2014/09/02 19:02:17 Error: failed to remove one or more containers 
</pre>

Follow panamax version:

<pre>
███████╗ ██████╗  █████████╗ ██████╗  ██████████╗ ██████╗  ██╗  ██╗
██╔══██║  ╚═══██╗ ███╗  ███║  ╚═══██╗ ██║ ██╔ ██║  ╚═══██╗ ╚██╗██╔╝
██   ██║ ███████║ ███║  ███║ ███████║ ██║╚██║ ██║ ███████║  ╚███╔╝ 
███████╝ ███████║ ███║  ███║ ███████║ ██║╚██║ ██║ ███████║  ██╔██╗ 
██║      ███████║ ███║  ███║ ███████║ ██║╚██║ ██║ ███████║ ██╔╝ ██╗
╚═╝      ╚══════╝ ╚══╝  ╚══╝ ╚══════╝ ╚═╝ ╚═╝ ╚═╝ ╚══════╝ ╚═╝  ╚═╝

CenturyLink Labs - http://www.centurylinklabs.com/

Checking if required software is installed.

Vagrant 1.6 or newer installed.
Virtualbox 4.2 or newer installed.

Local Panamax component versions:
   UI: 0.1.2
  API: 0.1.2
Local Panamax Installer version:
</pre>

Already tried reintalling like the following:

`lsoave@basenode:~$ panamax reinstall --cpu=2 --memory=2048`

UI & API containers are running fine:

<pre>
core@panamax-vm ~ $ docker ps -a
CONTAINER ID        IMAGE                            COMMAND                CREATED             STATUS              PORTS                     NAMES
9ebbbac8b000        centurylink/panamax-ui:latest    /bin/sh -c 'bundle e   4 minutes ago       Up 4 minutes        0.0.0.0:3000->3000/tcp    PMX_UI                         
9af4bcacf94d        centurylink/panamax-api:latest   /bin/sh -c 'bundle e   4 minutes ago       Up 4 minutes        0.0.0.0:3001->3000/tcp    PMX_API,PMX_UI/PMX_API         
826cb78c9ad0        google/cadvisor:0.1.0            /usr/bin/cadvisor      4 minutes ago       Up 4 minutes        0.0.0.0:49153->8080/tcp   PMX_CADVISOR,PMX_UI/CADVISOR   
</pre>

**Comment by skill83** [comment]
i also have the loop

```
ul 18 11:14:59 docker Status: Image is up to date for ubuntu:latest
Jul 18 11:14:59 systemd Started ubuntu_latest.service.
Jul 18 11:15:00 docker Error response from daemon: no such id: ubuntu_latest
Jul 18 11:15:00 docker time="2017-07-18T09:15:00Z" level=fatal msg="Error: failed to stop one or more containers"
```
