### ISSUE TITLE
Add instructions to install on DigitalOcean

### ISSUE THREAD

**Issue by thaJeztah** [CenturyLinkLabs/panamax-ui#351]
Now that CoreOs is (finally) available on DigitalOcean ([anouncement](https://www.digitalocean.com/company/blog/coreos-now-available-on-digitalocean/)), could instructions be added on how to install Panamax using DigitalOcean VPS?

**Comment by alias1** [comment]
Found this issue via google, and as best as I can see the digital ocean instructions aren't in the wiki anymore? Am I just blind, or are they gone for a reason?

**Comment by rossjimenez** [comment]
https://github.com/CenturyLinkLabs/panamax-ui/wiki/Cloud-Provider-Installation-of-Panamax-Client#digital-ocean  -> Since adding remote deployment capability the cloud provider installation instructions were moved as it is not the recommended way to run Panamax.
