### ISSUE TITLE
Any plans to implement some type of auth for Panamax-UI?

### ISSUE THREAD

**Issue by stela5** [CenturyLinkLabs/panamax-ui#366]
Your https://github.com/CenturyLinkLabs/panamax-ui/wiki/Installing-Panamax guide explicitly states that Panamax does not secure the UI with any default authentication mechanism.  Any plans to support auth options out of the box?  Or perhaps provide a wiki guide for implementing basic auth or OAuth?

**Comment by JulianKingman** [comment]
Oof. This is frustrating. I just went and got this set up on my server, and it works wonderfully! Now I discover that there's no way to prevent other people from logging in and changing things on my containers, or deleting them... did I miss something? I thought panamax could be used for managing containers on servers, but I now have the impression that it's just for sandboxing on a local machine.
