### ISSUE TITLE
ER: Github token/Add a new source workflow

### ISSUE THREAD

**Issue by arnos** [CenturyLinkLabs/panamax-ui#444]
These are closely related 

1. Is it possible to separate the add token from the save template workflow? -- I found it counter intuitive that I was trying to add a template source but couldn't add the token there
2. When managing adding a new source (blank repo) and it's not a valid template format is it possible to populate it with the default files to make it a valid template format (and not have the "not in gzip format")

**Comment by dkhunt27** [comment]
The tool is great, but I am in the same situation as arnos...I would need the ability to 
1) Add my companies private repo (an org private repo) to the available sources
2) Need to be able to save templates to my companies private repo (an org private repo)..current save only supports personal private repos

Any update on this?

**Comment by arnos** [comment]
Ironically the ui seems dated now if you compare it to lastbackend.com and
docker compose seems to become the standard in terms of configuring
multiple containers

**Comment by patocox** [comment]
Hey @dkhunt27,
Regarding issue #1, you can add your company's private registry to Panamax. Check out this wiki (https://github.com/CenturyLinkLabs/panamax-ui/wiki/How-to:-Add-Registries) with some instructions especially if you have it behind auth.

Hope that helps,
Pat

**Comment by arnos** [comment]
@patocox yes the private registries can be saved but the issue here the
templates (what distinguishes panamax) is still only available from github
public repos.

**Comment by JonaDupIO** [comment]
Hi.
Any changes about private repository?

**Comment by rossjimenez** [comment]
No plans to support private repositories.  Closing
