### ISSUE TITLE
More control over docker run and port options

### ISSUE THREAD

**Issue by pikeas** [CenturyLinkLabs/panamax-ui#489]
I'm using https://github.com/progrium/docker-consul and https://github.com/progrium/registrator, each of which requires a bit of configuration which cannot currently be done with Panamax:

- `-p 172.17.42.1:53L53/udp`. Panamax only allows numbers for the port field, which prevents mapping of non-0.0.0.0 IP addresses.
- `-h foo` (or in this case, `-h $HOSTNAME`). Panamax doesn't support assigning a hostname to a container.

Modifying the fleet service files only works temporarily - Panamax eventually restores them to their original state.

It would be really useful if Panamax added an "advanced" override which gives you full control over `docker run` arguments.

**Comment by patocox** [comment]
@pikeas Thanks for the suggestion. We have something similar in the UserVoice, if you would like to add your vote. http://feedback.panamax.io/forums/260899-general/suggestions/6394996-add-the-ability-to-manually-enter-docker-run-opti

**Comment by pikeas** [comment]
@patocox Why was this issue closed? Have these features been added to Panamax?

**Comment by patocox** [comment]
No, these have not been added to Panamax, but we keep feature requests like this in our UserVoice system and use that for tracking and prioritization.
