### ISSUE TITLE
execution expired

### ISSUE THREAD

**Issue by xirun** [CenturyLinkLabs/panamax-ui#492]
Hello , I came across a problem.
After I search one image and begin to run it up, Panamax shows execution expired. What should I do next?

**Comment by patocox** [comment]
Hi @xirun Can you snap a screenshot of the error? Also, can you give me the output of the `$ panamax debug`  from the command line?

Thanks,
Pat

**Comment by rossjimenez** [comment]
Closing... due to no user feedback.
