### ISSUE TITLE
not all available tags are shown in dropdown

### ISSUE THREAD

**Issue by leon** [CenturyLinkLabs/panamax-ui#493]
try searching for `dockerfile/java` that has a couple of different tags, but panamax only shows `latest`

```
Local Panamax component versions:
   UI: 0.2.11
  API: 0.2.11
Local Panamax Installer version:
  0.3.4
```

**Comment by patocox** [comment]
@leon Panamax loads the tags after you select the drop-down. I was able to bring them up. Let me know if they still dont load.
![screen shot 2015-01-20 at 10 30 13 am](https://cloud.githubusercontent.com/assets/2650116/5823074/686d4e88-a09f-11e4-9a5c-b64771871c76.png)

**Comment by allanlaal** [comment]
issue persists:

try searching for: webdevops/bootstrap
then click on Tags. nothing will appear

even though there are lots of tags: https://hub.docker.com/r/webdevops/bootstrap/tags/
