### ISSUE TITLE
panamax-vm: Warning: Authentication failure. Retrying...

### ISSUE THREAD

**Issue by GM-Alex** [CenturyLinkLabs/panamax-ui#494]
If I setup panamax everything works fine. If I halt the machine and restart it I get 

```
panamax-vm: Warning: Authentication failure. Retrying...
```

Than I have to reinstall panamax and it works again until the next halt. If I comment out ``config.ssh.username = "core"`` it works like charm.

**Comment by nugai** [comment]
The reason why that works (at least on the surface) is that, without a user specification, the SSH login does not use the private key generated during init and/or reinstall, but uses the Vagrant insecure key instead. 

The reason why that problem exists in the first is that, during a restart, the private key stored on the VM gets overwritten. I wrote about this problem (and how to work around it) in [this thread](https://github.com/CenturyLinkLabs/panamax-coreos/issues/63).

**Comment by patocox** [comment]
We released a fix for this in ver 0.3.5 of the panamax installer. Run `$ brew upgrade http://download.panamax.io/installer/brew/panamax.rb && panamax reinstall` to get the latest on Mac.
