### ISSUE TITLE
Problem setting network interfaces in panamax init

### ISSUE THREAD

**Issue by rklubenspies** [CenturyLinkLabs/panamax-ui#496]
Hey guys!

The `panamax init` command is throwing an error and quitting before everything gets set up. Something about the "host network collides with a non-hostonly network" (see below) when setting up the VM's network interfaces. Does anyone have any insight on why this is happening? I've included a dump from my terminal window below.

Thank you in advance for any help!

-Robert

```ShellSession
Roberts-MBP:~ robert$ brew install panamax
==> Downloading http://download.panamax.io/installer/panamax-0.3.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/panamax-0.3.4.tar.gz
==> ./configure --prefix=/usr/local/Cellar/panamax/0.3.4 --var=/usr/local/var/panamax
==> make install
==> Caveats
If upgrading the Panamax Installer, be sure to run 'panamax reinstall' to ensure compatibility with other Panamax components.
==> Summary
🍺  /usr/local/Cellar/panamax/0.3.4: 19 files, 116K, built in 2 seconds
Roberts-MBP:~ robert$ panamax init

███████╗ ██████╗  █████████╗ ██████╗  ██████████╗ ██████╗  ██╗  ██╗
██╔══██║  ╚═══██╗ ███╗  ███║  ╚═══██╗ ██║ ██╔ ██║  ╚═══██╗ ╚██╗██╔╝
██   ██║ ███████║ ███║  ███║ ███████║ ██║╚██║ ██║ ███████║  ╚███╔╝
███████╝ ███████║ ███║  ███║ ███████║ ██║╚██║ ██║ ███████║  ██╔██╗
██║      ███████║ ███║  ███║ ███████║ ██║╚██║ ██║ ███████║ ██╔╝ ██╗
╚═╝      ╚══════╝ ╚══╝  ╚══╝ ╚══════╝ ╚═╝ ╚═╝ ╚═╝ ╚══════╝ ╚═╝  ╚═╝

CenturyLink Labs - http://www.centurylinklabs.com/

Checking if required software is installed.

Vagrant 1.6 or newer installed.
Virtualbox 4.3 or newer installed.


Creating a new CoreOS VM...
UUID changed to: 07150a22-4070-42ed-a20c-c8d581d7d14c
Bringing machine 'panamax-vm' up with 'virtualbox' provider...
==> panamax-vm: Importing base box 'panamax-coreos-box-494.5.0'...
==> panamax-vm: Matching MAC address for NAT networking...
==> panamax-vm: Setting the name of the VM: panamax-vm
==> panamax-vm: Clearing any previously set network interfaces...
The specified host network collides with a non-hostonly network!
This will cause your specified IP to be inaccessible. Please change
the IP or name of your host only network so that it no longer matches that of
a bridged or non-hostonly network.
VM Creation failed. Exiting.
Roberts-MBP:~ robert$
```

**Comment by rklubenspies** [comment]
Here's a look at what `panamax init` configured in VirtualBox (through Vagrant, I believe) before quitting.
![screen shot 2015-01-23 at 7 02 49 pm](https://cloud.githubusercontent.com/assets/448701/5884943/852c7eaa-a332-11e4-9af6-27e7128e3fda.png)
I'm running Vagrant 1.7.2 and VirtualBox 4.3.20 with Mac OS X 10.10.1 as the host system.

**Comment by rklubenspies** [comment]
This had everything to do with my physical network's IP addresses. I found the solution at CenturyLinkLabs/panamax-coreos#52. I'm re-writing the instructions here for anyone who finds this issue. I tested this on Panamax 0.3.4 running on Mac OS X 10.10.1.

### How to fix "The specified host network collides with a non-hostonly network" error
This error means Vagrant couldn't setup the `panamax-vm` with the default private IP address of `10.0.0.200`. In my case, this happened because my physical network uses addresses like `10.0.0.112`. The good news is you can override the default private IP address used in setting up Panamax! Here's how:

1. Create a file at `/usr/local/var/panamax/.env` (on a Mac)
2. Add this line to the file: `export PMX_VM_PRIVATE_IP="100.0.0.0"`
  * Note: You can change that private IP address to anything you want, as long as it's not being used by your current network configuration.
3. Run `panamax init`.

I hope this is useful to anyone running into this issue!

A huge thank you to @cakkineni for helping me figure out how to fix this by diligently updating the instructions at CenturyLinkLabs/panamax-coreos#52 for version 0.3+.

**Comment by probepark** [comment]
:+1:
