### ISSUE TITLE
JavaScript Errors in Firefox

### ISSUE THREAD

**Issue by niclashoyer** [CenturyLinkLabs/panamax-ui#502]
The Panamax UI shows the following errors in the console on Firefox 35 and is not really functional:

```
TypeError: $(...).analyticsClickTracker is not a function
```
(init.js line 8)

Runs fine using Chromium 38.

**Comment by patocox** [comment]
@niclashoyer Im running 35.0.1 on OSX and Im not seeing any error. Seems to be running fine. Is there a particular page you are seeing this? Could a plug-in/extension be causing the error?

Thanks,
Pat

**Comment by niclashoyer** [comment]
Yes, you are right. It was an adblocker extension.
