### ISSUE TITLE
How to change allocated memory without reinstall 

### ISSUE THREAD

**Issue by yurevichcv** [CenturyLinkLabs/panamax-ui#507]
Documentation says:
> manually edit the PMX_VM_MEMORY and PMX_VM_CPUS entries in the ~/.panamax/.env file.

But actually panamax is installed in `/usr/local/opt/panamax/.panamax/` folder and there is no `.env` file inside.

**Comment by patocox** [comment]
@yurevichcv Bad docs. Will get them corrected.
The path of the .env file is: `$ /usr/local/var/panamax/.env`. 
You can change the RAM/CPU there and then perform a `$ panamax restart` for the changes to take affect.

Thanks,
Pat
