### ISSUE TITLE
The specified host network collides with a non-hostonly network!

### ISSUE THREAD

**Issue by savingschampion** [CenturyLinkLabs/panamax-ui#509]
We use 10.0.0.x internally as private LAN IP address space.

It appears that panamax is also doing the same for host-only-networking

Error returned:

```
The specified host network collides with a non-hostonly network!
This will cause your specified IP to be inaccessible. Please change
the IP or name of your host only network so that it no longer matches that of
a bridged or non-hostonly network.
```

**Comment by patocox** [comment]
Ok - best bet is to change it... go to /usr/local/var/panamax/.env and make the change. Do a `$ panamax restart` for the change to take affect.

-PC

**Comment by savingschampion** [comment]
I made a change to desktop instead, which also worked

**Comment by patocox** [comment]
Good to hear. Closing the issue.

**Comment by joost** [comment]
For future readers:
Fix the issue by adding this to `/usr/local/var/panamax/.env`:

    PMX_VM_PRIVATE_IP="10.1.0.0"

Use some IP that is not in your current network.
