### ISSUE TITLE
brew tap instead of direct formula installation

### ISSUE THREAD

**Issue by caktux** [CenturyLinkLabs/panamax-ui#514]
Please create a `homebrew-panamax` repo to host the homebrew formula, that way we'll be able to install using
```
brew tap CenturyLinkLabs/panamax
brew install panamax
```
It'll also allow upgrading using the regular brew update & upgrade procedure.

**Comment by rheinwein** [comment]
Hi @caktux -- we would love to have a brew formula, but it needs to be submitted by the community and not by us. If you'd like to submit a formula, we'd be happy to collaborate with you!

**Comment by rossjimenez** [comment]
Closing.
