### ISSUE TITLE
Some buttons don't works

### ISSUE THREAD

**Issue by Santinell** [CenturyLinkLabs/panamax-ui#517]
I successfully install panamax on coreOS 633 in digitalocean
After that tryed create app, but most buttons don't work:
- "Add a New Source" (http://xxxxxxx:3000/template_repos)
- edit category in app (http://xxxxxxx:3000/apps/1)
- "Add a Category" in app (http://xxxxxxx:3000/apps/1)
- "Add a Service" in app (http://xxxxxxx:3000/apps/1)

no error messages, just ignoring clicking on buttons

**Comment by Santinell** [comment]
I found the reason of problems - uBlock Chrome pugin
for some reason, he blocked panamax js scripts

**Comment by patocox** [comment]
Cool. Glad you were able to resolve the issue!
