### ISSUE TITLE
Installation Steps

### ISSUE THREAD

**Issue by radiumx3** [CenturyLinkLabs/panamax-ui#518]
Just wondering why doesnt we get a full and clean installation tutorial, instead of having to deploy VM's from a vagrant box ...

All the more we allready have docker installed on our host. Is it planned to get detailled tutorial on how to install panamax for experienced users ^_^ ?

**Comment by beeyeas** [comment]
Also a 10 some minute video for installation steps is asking for too much of time.
A simple ~5 step is what is needed.

**Comment by radiumx3** [comment]
:+1:

**Comment by nvivo** [comment]
Any news on this? I'm trying to test panamax on digital ocean.

Is it possible to provide some simple instructions on how to deploy it to a server without vagrant?

**Comment by patocox** [comment]
Hi @nvivo You can install Panamax directly on Digital Ocean by following these instructions: https://github.com/CenturyLinkLabs/panamax-ui/wiki/Cloud-Provider-Installation-of-Panamax-Client#digital-ocean

**Comment by rossjimenez** [comment]
Closed
