### ISSUE TITLE
Allow insecure docker registries

### ISSUE THREAD

**Issue by andredasilvapinto** [CenturyLinkLabs/panamax-ui#536]
According to the documentation, in order to enable insecure docker registries, we should pick that option during setup or reinstallation when prompted (it is said we should pick Y). However, there is no such prompt. 

How can I allow insecure docker registries? 

https://github.com/CenturyLinkLabs/panamax-ui/wiki/How-to:-Add-Registries#insecure-and-secure-registries

**Comment by andredasilvapinto** [comment]
By looking at .panamax/desktop file I've managed to understand that that option is only show when you run: panamax without any positional argument and then pick the reinstall or install option.

I would suggest you to change the documentation as it tells people to use panamax reinstall:

```
To change your setting, run $ panamax reinstall from a command prompt.
```

and that doesn't let the user pick that option.

**Comment by cakkineni** [comment]
@andredasilvapinto 

Thank you for the input, updated the documentation page to indicate the possible options.
