### ISSUE TITLE
Failed to connect to stable.release.core-os.net port 80: Operation timed out

### ISSUE THREAD

**Issue by summer-wu** [CenturyLinkLabs/panamax-ui#545]
I am in china,the core-os.net is slow. May I download it on other site  then pass the file location in command line? 
eg: $panamax init --coreosfile /Users/mike/coreos.box

**Comment by cakkineni** [comment]
hi @summer-wu 

You can download the vagrant box and name it, `panamax-coreos-box-681.2.0`, then panamax will use that. Be sure to download CoreOS 681.2.0.

**Comment by summer-wu** [comment]
i have resolved the problem. thank you @cakkineni .
1.  manaual download the box file from http://stable.release.core-os.net/amd64-usr/681.2.0/coreos_production_vagrant.box
2. place it under ~/box. The directory name can be anything.
3. `$ cd ~/box`
4. `$ vagrant box add panamax-coreos-box-681.2.0 coreos_production_vagrant.box` 
5. `$ vagrant box list` ensure there has an item named `panamax-coreos-box-681.2.0 `
6. `$ panamax init`
