### ISSUE TITLE
Progress stalled on Digital Ocean: docker pull centurylink/panamax-api:latest

### ISSUE THREAD

**Issue by JulianKingman** [CenturyLinkLabs/panamax-ui#550]
I waited for what seemed like an unreasonable amount of time, and it never moved on to the next step. By contrast, setting it up on a local VM was speedy (although I have other problems there). 

````
docker pull centurylink/panamax-api:latest
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................^C
````

I followed the instructions for CoreOS, is there something I'm missing? Why would it be taking forever on this step? Maybe a port issue? I don't know how to make sure the ports are open, but it's a fresh install so I would assume the configuration would work out of the box. It's CoreOS 829.0.0

**Comment by JulianKingman** [comment]
I downgraded my coreos version to the stable one and it worked.

**Comment by davidgardner11** [comment]
Glad to hear you were able to resolve the issue. Downgrading to prior releases is a lot easier with containerized software, and is often a good first step when troubleshooting.
