### ISSUE TITLE
is this still maintaned ? 

### ISSUE THREAD

**Issue by dimthe** [CenturyLinkLabs/panamax-ui#571]
hello is panamax still maintained ? I am only asking because most of the issues i see are from a year + or so ago

**Comment by MadOtis** [comment]
I don't think so.  I haven't seen a single update in about 8-10 months.  You may want to take a look at Rancher instead (rancher.com), not perfectly the same, but is very well maintained and extremely useable.

**Comment by pedrofurtado** [comment]
@dimthe There are very good alternatives:

Portainer -> https://github.com/portainer/portainer
Rancher -> https://github.com/rancher/rancher
